services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    platform: linux/arm64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
      - chatbox
    networks:
      - app-network
    restart: always

  backend:
    container_name: backend
    image: ${DOCKERHUB_NAMESPACE:-chinhps}/base-backend-api:latest
    platform: linux/arm64
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      - APP_ENV=production
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - APP_PORT=${APP_PORT:-3000}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - ARTICLE_SERVICE_HOST=${SOCIAL_HOST:-social-network}
      - ARTICLE_SERVICE_PORT=${SOCIAL_PORT:-3001}
      - CHATBOX_HOST=${CHATBOX_HOST:-chatbox}
      - CHATBOX_TCP_PORT=${CHATBOX_TCP_PORT:-3003}
      - JWT_SECRET_PRIVATEKEY=${JWT_SECRET_PRIVATEKEY}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_TOKEN_EXPIRES_IN=${JWT_REFRESH_TOKEN_EXPIRES_IN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - MAILER_DSN=${MAILER_DSN}
      - RECOMMEND_SERVICE_HOST=${RECOMMEND_HOST:-recommend-service}
      - RECOMMEND_SERVICE_PORT=${RECOMMEND_TCP_PORT:-8866}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    networks:
      - app-network

  frontend:
    container_name: frontend
    image: ${DOCKERHUB_NAMESPACE:-chinhps}/booking-nextjs:latest
    platform: linux/arm64
    restart: always
    environment:
      - NODE_ENV=production
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - API_BACKEND_CONTAINER=${API_BACKEND_CONTAINER}
      - NEXT_PUBLIC_API_BACKEND=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - NEXT_PUBLIC_CHATBOX_WS_URL=${NEXT_PUBLIC_CHATBOX_WS_URL}
      - AUTH_URL=${NEXT_PUBLIC_APP_URL}/api/auth
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:8.0
    platform: linux/arm64
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  social-network:
    container_name: social-network
    image: ${DOCKERHUB_NAMESPACE:-chinhps}/booking-social-service:latest
    platform: linux/arm64
    restart: always
    depends_on:
      - mongo
    environment:
      - APP_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${SOCIAL_PORT:-3001}
    networks:
      - app-network
    
  chatbox:
    container_name: chatbox
    image: ${DOCKERHUB_NAMESPACE:-chinhps}/chatbox-module:latest
    platform: linux/arm64
    restart: always
    depends_on:
      - mongo
    environment:
      - APP_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${CHATBOX_PORT:-3002}
      - CHATBOX_TCP_PORT=${CHATBOX_TCP_PORT:-3003}
      - JWT_SECRET_PRIVATEKEY=${JWT_SECRET_PRIVATEKEY}
      - AI_SERVICE_HOST=${AI_HOST:-python-ai-service}
      - AI_SERVICE_PORT=${AI_PORT:-8000}
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:4.4.18
    platform: linux/arm64
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    platform: linux/arm64
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app-network

  recommend-service:
    container_name: recommend-service
    image: ${DOCKERHUB_NAMESPACE:-chinhps}/recommend-module:latest
    platform: linux/arm64
    restart: always
    depends_on:
      - mongo
    environment:
      - APP_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${RECOMMEND_PORT:-8865}
      - RECOMMEND_TCP_PORT=${RECOMMEND_TCP_PORT:-8866}
    networks:
      - app-network

  python-ai-service:
    container_name: python-ai-service
    image: ${DOCKERHUB_NAMESPACE:-chinhps}/python-ai-service:latest
    platform: linux/arm64
    restart: always
    volumes:
      # link model in production
      - /home/chinhdev/docker/models/qwen2.5-1.5b-tour-assistant-q4.gguf:/usr/src/app/model/qwen2.5-1.5b-tour-assistant-q4.gguf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  mongo-data:
  redis-data:
