services:
  backend:
    container_name: backend
    build:
      context: ../backend-booking-tour
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    restart: always
    volumes:
      - ../backend-booking-tour:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    environment:
      - APP_ENV=${APP_ENV}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - DB_CONNECTION=${DB_CONNECTION}
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - ARTICLE_SERVICE_HOST=${ARTICLE_SERVICE_HOST}
      - ARTICLE_SERVICE_PORT=${ARTICLE_SERVICE_PORT}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - JWT_SECRET_PRIVATEKEY=${JWT_SECRET_PRIVATEKEY}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_TOKEN_EXPIRES_IN=${JWT_REFRESH_TOKEN_EXPIRES_IN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ../booking-nextjs
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ../booking-nextjs:/app
      - /app/node_modules
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - API_BACKEND_CONTAINER=${API_BACKEND_CONTAINER}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_API_BACKEND=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  social-network:
    container_name: social-network
    build:
      context: ../social-network
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - ../social-network:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${ARTICLE_SERVICE_PORT}
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  mongo-data:
